In [2]:
# Imports
import polars as pl
import pandas as pd
import numpy as np
import json
import re

In [3]:
norm = pl.read_parquet('./data/normalized_data.parquet')

# Check for null or nan values in norm
norm.filter(pl.any_horizontal(pl.col(pl.Float64).is_null() | pl.col(pl.Float64).is_nan()))

# Remove nulls
norm = norm.filter(~pl.any_horizontal(pl.col(pl.Float64).is_null() | pl.col(pl.Float64).is_nan()))

# Making Polars DataFrame where each row is a pitch
    # (i.e. x_marker_frame, y_marker_frame, z_marker_frame are columns made from x, y, z, frame, and markerID columns of df)
def create_pitch_df(df):
    # Create a Polars DataFrame where each row is a pitch
    pitch_df = df.pivot(
        index = ["userID", "sessionID", "pitchNum", "height", "weight", "pitchType", "pitchSpeed", "p_throws"],
        on = ['markerID', 'frame_norm'],
        values = ['x', 'y', 'z']
    )
    
    # Pattern to match x_{"C7",0} or similar
    pattern = re.compile(r'([xyz])_\{"([^"]+)",(\d+)\}')

    # Change from naming convention of x_{"C7",0} to x_C7_0 
    for col in pitch_df.columns:
        if col.startswith('x_') or col.startswith('y_') or col.startswith('z_'):
            match = pattern.match(col)
            axis, marker, frame = match.groups()
            new_col_name = f"{axis}_{marker}_{frame}"
            pitch_df = pitch_df.rename({col: new_col_name})

    return pitch_df

# Create PCA-ready DataFrame
df = create_pitch_df(norm)
#df = pl.read_parquet('./data/pca_ready_data.parquet')
df.head()

shape: (5, 13_340)
┌────────┬───────────┬──────────┬────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ userID ┆ sessionID ┆ pitchNum ┆ height ┆ … ┆ z_T10_97 ┆ z_T10_98 ┆ z_T10_99 ┆ z_T10_100 │
│ ---    ┆ ---       ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str    ┆ str       ┆ str      ┆ str    ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64       │
╞════════╪═══════════╪══════════╪════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 001663 ┆ 002979    ┆ 002      ┆ 79     ┆ … ┆ 1.222977 ┆ 1.23271  ┆ 1.240368 ┆ 1.245988  │
│ 001592 ┆ 002815    ┆ 005      ┆ 75     ┆ … ┆ 0.975924 ┆ 0.995345 ┆ 1.006016 ┆ 1.009646  │
│ 001606 ┆ 002833    ┆ 006      ┆ 71     ┆ … ┆ 1.027843 ┆ 1.030689 ┆ 1.034211 ┆ 1.036295  │
│ 001466 ┆ 002653    ┆ 006      ┆ 75     ┆ … ┆ 1.126593 ┆ 1.130946 ┆ 1.136636 ┆ 1.144225  │
│ 001641 ┆ 002923    ┆ 008      ┆ 70     ┆ … ┆ 1.01799  ┆ 1.021983 ┆ 1.026618 ┆ 1.031384  │
└────────┴───────────┴──────────┴────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [4]:
def convert_real_df_to_json(df: pl.DataFrame, output_filename="real_data.json"):
    # Ensure correct types
    df = df.with_columns([
        pl.col("frame_norm").cast(pl.Int64),
        pl.col("pitchNum").cast(pl.Int64),
        pl.col("x").cast(pl.Float64),
        pl.col("y").cast(pl.Float64),
        pl.col("z").cast(pl.Float64),
    ])

    # Group by pitch
    grouped = df.group_by(["userID", "sessionID", "pitchNum"]).agg([
        pl.first("pitchType").alias("pitchType"),
        pl.first("pitchSpeed").alias("pitchSpeed"),
        (pl.max("frame_norm") + 1).cast(pl.Int64).alias("max_frames"),
        pl.struct(["frame_norm", "markerID", "x", "y", "z"]).alias("points")
    ])

    pitches = []

    # Convert to JSON structure
    for row in grouped.iter_rows(named=True):
        frames = {}
        for p in row["points"]:
            f = int(p["frame_norm"])
            marker = p["markerID"]
            if f not in frames:
                frames[f] = {}
            frames[f][marker] = {
                "x": float(p["x"]),
                "y": float(p["y"]),
                "z": float(p["z"])
            }

        pitches.append({
            "id": f"{row['userID']}_{row['sessionID']}_{row['pitchNum']}",
            "label": f"U:{row['userID']} S:{row['sessionID']} P:{row['pitchNum']} "
                     f"({row['pitchType']} @ {row['pitchSpeed']}mph)",
            "max_frames": int(row["max_frames"]),
            "frames": frames
        })

    # Write JSON
    with open(output_filename, "w") as f:
        json.dump(pitches, f)

convert_real_df_to_json(norm)

In [5]:
# Filter rows where any value is null or NaN
df = df.filter(
    ~(
    pl.any_horizontal(
        # Check for missing data AND for floating point NaN
        pl.nth(range(8, len(df.columns))).is_null() | 
        pl.nth(range(8, len(df.columns))).is_nan()
    )
    )
)

df.head()

shape: (5, 13_340)
┌────────┬───────────┬──────────┬────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ userID ┆ sessionID ┆ pitchNum ┆ height ┆ … ┆ z_T10_97 ┆ z_T10_98 ┆ z_T10_99 ┆ z_T10_100 │
│ ---    ┆ ---       ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str    ┆ str       ┆ str      ┆ str    ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64       │
╞════════╪═══════════╪══════════╪════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 001663 ┆ 002979    ┆ 002      ┆ 79     ┆ … ┆ 1.222977 ┆ 1.23271  ┆ 1.240368 ┆ 1.245988  │
│ 001592 ┆ 002815    ┆ 005      ┆ 75     ┆ … ┆ 0.975924 ┆ 0.995345 ┆ 1.006016 ┆ 1.009646  │
│ 001606 ┆ 002833    ┆ 006      ┆ 71     ┆ … ┆ 1.027843 ┆ 1.030689 ┆ 1.034211 ┆ 1.036295  │
│ 001466 ┆ 002653    ┆ 006      ┆ 75     ┆ … ┆ 1.126593 ┆ 1.130946 ┆ 1.136636 ┆ 1.144225  │
│ 001641 ┆ 002923    ┆ 008      ┆ 70     ┆ … ┆ 1.01799  ┆ 1.021983 ┆ 1.026618 ┆ 1.031384  │
└────────┴───────────┴──────────┴────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [55]:
# Taking transpose of the PCA-ready DataFrame to get the data in the correct format for PCA
    # (n_pitches, 3 * n_markers * n_frames)

X = df.select(pl.nth(range(8, len(df.columns)))).to_numpy().T

X_mean = np.mean(X, axis=1, keepdims = True)
X_centered = X - X_mean

cov_mat = (X_centered.T @ X_centered) / (X_centered.shape[1] - 1)
print(cov_mat.shape)

eigenvalues, eigenvectors = np.linalg.eigh(cov_mat)

idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

for i, eval, evec in zip(range(len(eigenvectors)), eigenvalues, eigenvectors.T):
    if i < 5:
        print(f"Eigenvalue: {np.round(eval,3)}, Eigenvector: {evec[:2]} ... [{evec[-1]}]")

(410, 410)
Eigenvalue: 112.782, Eigenvector: [ 0.03523557 -0.0756251 ] ... [0.09841981973225843]
Eigenvalue: 53.814, Eigenvector: [-0.08299333 -0.04061427] ... [0.06896826452784909]
Eigenvalue: 28.059, Eigenvector: [ 0.04161906 -0.05704452] ... [-0.05393539531386199]
Eigenvalue: 18.212, Eigenvector: [-0.0984126  -0.07559587] ... [0.03105824375360148]
Eigenvalue: 16.215, Eigenvector: [ 0.04602996 -0.04745273] ... [-0.07351174038448217]

In [56]:
# Calculate Explained Variance Ratio
total_variance = np.sum(eigenvalues)
explained_variance_ratio = eigenvalues / total_variance

# Calculate Cumulative Explained Variance
cumulative_variance = np.cumsum(explained_variance_ratio)

# Print results
for i, (eval, ratio) in enumerate(zip(eigenvalues, explained_variance_ratio)):
    print(f"PC{i+1}: Eigenvalue: {eval:.4f}, Variance Explained: {ratio:.2%}")
    if cumulative_variance[i] > 0.80:  # Stop showing once we hit 90%
        print(f"--- 80% variance reached at PC{i+1} ---")
        # Selecting top i principal components needed to get 90% of variance
        k = i + 1
        U = eigenvectors[:, :k]          # (M, k)
        Lambda = eigenvalues[:k]         # (k,)
        eps = 1e-12
        V = X_centered @ U / np.sqrt((X_centered.shape[1] - 1) * (Lambda + eps))
        break

PC1: Eigenvalue: 112.7825, Variance Explained: 33.60%
PC2: Eigenvalue: 53.8136, Variance Explained: 16.03%
PC3: Eigenvalue: 28.0585, Variance Explained: 8.36%
PC4: Eigenvalue: 18.2119, Variance Explained: 5.43%
PC5: Eigenvalue: 16.2154, Variance Explained: 4.83%
PC6: Eigenvalue: 12.0844, Variance Explained: 3.60%
PC7: Eigenvalue: 9.3025, Variance Explained: 2.77%
PC8: Eigenvalue: 7.6881, Variance Explained: 2.29%
PC9: Eigenvalue: 7.6153, Variance Explained: 2.27%
PC10: Eigenvalue: 5.4518, Variance Explained: 1.62%
--- 80% variance reached at PC10 ---

In [57]:
pca_export = {
    'X_mean': X_mean.squeeze().tolist(),          # (M,)
    'V': V.tolist(),                              # (M, k)
    'Lambda': Lambda.tolist(),                    # (k,)
    'feature_names': df.columns[8:],     # length M
    'marker_labels': norm.select(pl.col('markerID')).unique().to_series().to_list(),     # length n_markers
    'n_frames': 101,
}

with open('pca_data.json', 'w') as f:
    json.dump(pca_export, f)

In [58]:
def get_pca_scores_for_pitch(
    pitch_features,
    X_mean,
    V_components,
    Lambda
):
    """
    Returns variance-standardized PCA scores (z-scores).
    """
    pitch_vector = pitch_features.reshape(-1, 1)
    pitch_centered = pitch_vector - X_mean

    # Raw PCA coordinates
    raw_scores = V_components.T @ pitch_centered  # (k, 1)

    # Variance-standardized scores
    z_scores = raw_scores.flatten() / np.sqrt(Lambda)

    return z_scores



def compute_pca_scores_dataframe(df_pitches, X_mean, V_components, Lambda, n_training_samples):
    """
    Computes PCA scores for all pitches and returns as a dataframe.
    
    Args:
        df_pitches: Polars DataFrame with pitch data (from create_pitch_df)
        X_mean: global mean vector (shape: D, 1)
        V_components: principal components in feature space (shape: D, k)
        Lambda: eigenvalues (shape: k,)
        n_training_samples: number of training samples
    
    Returns:
        Polars DataFrame with columns:
        [userID, sessionID, pitchNum, pitchSpeed, PC1_Score, PC2_Score, ..., PC{k}_Score]
    """
    # Get feature columns (indices 8 onwards)
    feature_cols = df_pitches.columns[8:]
    metadata_cols = ["userID", "sessionID", "pitchNum", "pitchSpeed"]
    
    # Extract metadata
    metadata = df_pitches.select(metadata_cols)
    
    # Extract features as numpy array
    features_np = df_pitches.select(feature_cols).to_numpy()
    
    print(f"Computing PCA scores for {features_np.shape[0]} pitches...")
    
    # Compute PCA scores for all pitches
    pca_scores_list = []
    for i, pitch_features in enumerate(features_np):
        scores = get_pca_scores_for_pitch(pitch_features, X_mean, V_components, Lambda)

        pca_scores_list.append(scores)
        
        if (i + 1) % 50 == 0:
            print(f"  Computed scores for {i + 1}/{len(features_np)} pitches")
    
    # Convert scores to numpy array (n_pitches, k)
    pca_scores_array = np.array(pca_scores_list)
    
    # Create dataframe with PC columns
    k = pca_scores_array.shape[1]
    pc_column_names = [f"PC{i+1}_Score" for i in range(k)]
    
    # Convert to Polars DataFrame
    pc_df = pl.DataFrame({
        pc_column_names[i]: pca_scores_array[:, i].tolist() 
        for i in range(k)
    })
    
    # Combine metadata and PC scores
    result_df = pl.concat([metadata, pc_df], how="horizontal")
    
    print(f"Complete! Result shape: {result_df.shape}")
    print(f"Columns: {result_df.columns}")
    
    return result_df


# ============================================================================
# MAIN: Compute and save results
# ============================================================================

# Compute V_components (principal components in feature space)
eps = 1e-12
V_components = X_centered @ U / np.sqrt((X_centered.shape[1] - 1) * (Lambda + eps))
# V_components shape: (D, k)

print("Computing PCA scores for all pitches...")
pca_df = compute_pca_scores_dataframe(df, X_mean, V_components, Lambda, X_centered.shape[1])
pca_df.head()

Computing PCA scores for all pitches...
Computing PCA scores for 410 pitches...
  Computed scores for 50/410 pitches
  Computed scores for 100/410 pitches
  Computed scores for 150/410 pitches
  Computed scores for 200/410 pitches
  Computed scores for 250/410 pitches
  Computed scores for 300/410 pitches
  Computed scores for 350/410 pitches
  Computed scores for 400/410 pitches
Complete! Result shape: (410, 14)
Columns: ['userID', 'sessionID', 'pitchNum', 'pitchSpeed', 'PC1_Score', 'PC2_Score', 'PC3_Score', 'PC4_Score', 'PC5_Score', 'PC6_Score', 'PC7_Score', 'PC8_Score', 'PC9_Score', 'PC10_Score']

shape: (5, 14)
┌────────┬───────────┬──────────┬────────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ userID ┆ sessionID ┆ pitchNum ┆ pitchSpeed ┆ … ┆ PC7_Score ┆ PC8_Score ┆ PC9_Score ┆ PC10_Score │
│ ---    ┆ ---       ┆ ---      ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ str    ┆ str       ┆ str      ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞════════╪═══════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 001663 ┆ 002979    ┆ 002      ┆ 84.9       ┆ … ┆ 0.153786  ┆ -0.439434 ┆ 0.054025  ┆ -1.2867    │
│ 001592 ┆ 002815    ┆ 005      ┆ 89.6       ┆ … ┆ 0.384568  ┆ 1.528992  ┆ -1.378017 ┆ 0.121567   │
│ 001606 ┆ 002833    ┆ 006      ┆ 85.5       ┆ … ┆ -0.539518 ┆ -0.104324 ┆ -0.770509 ┆ 0.731388   │
│ 001466 ┆ 002653    ┆ 006      ┆ 87.7       ┆ … ┆ 1.86348   ┆ 0.129338  ┆ 1.725385  ┆ 0.204735   │
│ 001641 ┆ 002923    ┆ 008      ┆ 76.3       ┆ … ┆ 0.980386  ┆ -0.22996  ┆ -0.083093 ┆ -1.157823  │
└────────┴───────────┴──────────┴────────────┴───┴───────────┴───────────┴───────────┴────────────┘

In [59]:
poi = pca_df.filter(
    (pl.col("userID") == "001000") & 
    (pl.col("sessionID") == "001718") & 
    (pl.col("pitchNum") == "006")
)
poi

shape: (1, 14)
┌────────┬───────────┬──────────┬────────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ userID ┆ sessionID ┆ pitchNum ┆ pitchSpeed ┆ … ┆ PC7_Score ┆ PC8_Score ┆ PC9_Score ┆ PC10_Score │
│ ---    ┆ ---       ┆ ---      ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ str    ┆ str       ┆ str      ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞════════╪═══════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 001000 ┆ 001718    ┆ 006      ┆ 90.8       ┆ … ┆ -0.612592 ┆ -1.075636 ┆ 2.163856  ┆ 0.227288   │
└────────┴───────────┴──────────┴────────────┴───┴───────────┴───────────┴───────────┴────────────┘