In [1]:
from scipy.interpolate import interp1d
import polars as pl
import pandas as pd
import numpy as np
import json

In [ ]:
# Polars
df = pl.read_parquet('./data/pitching_data.parquet')
df.head()

In [ ]:
# Both
print("Loading in pitch marker mapping")
# Load in pitch_marker_mapping
with open("./data/pitch_marker_mapping.json", 'r') as f:
    pitch_marker_mapping = json.load(f)

# Polars
print("Converting pitch marker mapping into a Polars DataFrame")
# Unroll the JSON mapping into a DataFrame
mapping_records = []
for pitch_key, labels in pitch_marker_mapping.items():
    for marker_id, marker_label in enumerate(labels):
        mapping_records.append({
            "pitch_key": pitch_key,
            "markerID": marker_id,
            "markerLabel": marker_label
        })
mapping_df = pl.DataFrame(mapping_records)

In [ ]:
# Create a key to merge data with marker mapping
df = df.with_columns(
    (
    df['userID'].cast(pl.Utf8) + '_' +
    df['sessionID'].cast(pl.Utf8) + '_' +
    df['pitchNum'].cast(pl.Utf8)
    ).alias('pitch_key')
)

In [ ]:
print("Merging data with marker mapping")
# Merge data with marker mapping
df = df.join(
    mapping_df,
    on = ['pitch_key', 'markerID'],
    how = 'inner' # Only keeping markers that have a label
)

In [ ]:
print("Replacing markerID number with markerLabel description as markerID")
# Drop original ID, replace and rename with label
df = df.drop(['markerID'])
df = df.with_columns(
    df['markerLabel'].str.split('_')
    .list.get(-1)
    .alias('markerLabel')
)
df = df.rename({'markerLabel': 'markerID'})

In [ ]:
print("Loading in poi_metrics, getting unique session-key pitcher-handedness combinations")
# Loading points of interest data, which contains pitcher handedness
poi_metrics = pl.read_csv("./data/poi_metrics.csv")[["session_pitch", "session", "p_throws", "pitch_speed_mph"]]
poi_metrics = poi_metrics.with_columns(
    poi_metrics["session"].cast(pl.Utf8)
    .alias('session_key')
)
# Drop duplicates
poi_metrics_unique = poi_metrics.unique(subset = ['session_key', 'p_throws'])

In [ ]:
print("Merging marker data with handedness")
# Merging marker data with pitcher handedness data
df = df.with_columns(
    df['sessionID'].cast(pl.Utf8)
    .str.replace(r"^0+", "")
    .alias('session_key')
)
df = df.join(
    poi_metrics_unique,
    on = 'session_key',
    how = 'left'
)

In [ ]:
def swap_lr(label):
    if label.startswith("L"):
        return "R" + label[1:]
    if label.startswith("R"):
        return "L" + label[1:]
    return label

print("Mirroring left-handed pitchers about the y-axis")
# Mirror lefties about the y-axis -- Now every pitcher is treated as being the same handedness (right-handed)
mask = pl.col("p_throws") == "L"

df = df.with_columns([
    pl.when(mask)
      .then(pl.col("y") * -1)
      .otherwise(pl.col("y"))
      .alias("y"),

    pl.when(mask)
      .then(pl.col("markerID").map_elements(swap_lr,  return_dtype = pl.Utf8))
      .otherwise(pl.col("markerID"))
      .alias("markerID"),
])

In [ ]:
print("Removing markers that are not present in every pitch")
# Identify unique markers per pitch
pitch_marker_sets = (
    df.group_by(["userID", "sessionID", "pitchNum"]).agg(
        pl.col('markerID').unique()
    )
)
# All markers in original data
all_markers = set(df["markerID"].unique())

# Intersect all marker sets to find markers present in every pitch
common_markers = set.intersection(*[set(x) for x in pitch_marker_sets["markerID"]])

# Markers that were excluded
excluded_markers = all_markers - common_markers
print(f"Removed {excluded_markers} from marker set for consistency")

# Filter data to only include markers present in every pitch
df = df.filter(pl.col('markerID').is_in(list(common_markers)))

# Dropping redundant columns
df = df.drop(['session_key', 'pitch_key', 'session_pitch', 'session', 'pitch_speed_mph'])

print('Saving cleaned data to cleaned_data2.parquet')
df.write_parquet('./data/cleaned_data2.parquet')

In [2]:
data = pl.read_parquet('./data/cleaned_data2.parquet')
data.head()

shape: (5, 13)
┌────────┬───────────┬────────┬────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ userID ┆ sessionID ┆ height ┆ weight ┆ … ┆ y         ┆ z        ┆ markerID ┆ p_throws │
│ ---    ┆ ---       ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str       ┆ str    ┆ str    ┆   ┆ f64       ┆ f64      ┆ str      ┆ str      │
╞════════╪═══════════╪════════╪════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.068032 ┆ 1.581415 ┆ C7       ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.186507 ┆ 1.495219 ┆ CLAV     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ 0.22933   ┆ 0.071697 ┆ LANK     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.112121 ┆ 1.040045 ┆ LASI     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.085127 ┆ 1.731568 ┆ LBHD     ┆ R        │
└────────┴───────────┴────────┴────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [3]:
import polars as pl
import numpy as np
from scipy.interpolate import interp1d

def normalize_frames_polars_interpolate(df: pl.DataFrame, N_TARGET_FRAMES: int = 101) -> pl.DataFrame:
    all_groups = []

    # Target normalized frame axis
    frame_norm = np.linspace(0, 100, N_TARGET_FRAMES)

    # Loop over each pitch explicitly
    for pitch_key, group in df.group_by(["userID", "sessionID", "pitchNum"]):
        # Process each marker separately
        for marker, marker_df in group.partition_by("markerID", as_dict=True).items():
            marker_df = marker_df.sort("frame")
            n_frames = marker_df.height
            if n_frames == 1:
                # single frame → replicate values
                interp_x = np.full(N_TARGET_FRAMES, marker_df["x"][0])
                interp_y = np.full(N_TARGET_FRAMES, marker_df["y"][0])
                interp_z = np.full(N_TARGET_FRAMES, marker_df["z"][0])
            else:
                # Original frame axis scaled 0–100
                orig_frames = np.linspace(0, 100, n_frames)
                interp_x = np.interp(frame_norm, orig_frames, marker_df["x"].to_numpy())
                interp_y = np.interp(frame_norm, orig_frames, marker_df["y"].to_numpy())
                interp_z = np.interp(frame_norm, orig_frames, marker_df["z"].to_numpy())

            # Build new DataFrame for this marker
            new_df = pl.DataFrame({
                "userID": pl.Series([marker_df["userID"][0]] * N_TARGET_FRAMES),
                "sessionID": pl.Series([marker_df["sessionID"][0]] * N_TARGET_FRAMES),
                "height": pl.Series([marker_df["height"][0]] * N_TARGET_FRAMES),
                "weight": pl.Series([marker_df["weight"][0]] * N_TARGET_FRAMES),
                "pitchNum": pl.Series([marker_df["pitchNum"][0]] * N_TARGET_FRAMES),
                "pitchType": pl.Series([marker_df["pitchType"][0]] * N_TARGET_FRAMES),
                "pitchSpeed": pl.Series([marker_df["pitchSpeed"][0]] * N_TARGET_FRAMES),
                "frame_norm": pl.Series(frame_norm).cast(pl.Int64),
                "x": pl.Series(interp_x),
                "y": pl.Series(interp_y),
                "z": pl.Series(interp_z),
                "markerID": pl.Series([marker][0] * N_TARGET_FRAMES),
                "p_throws": pl.Series([marker_df["p_throws"][0]] * N_TARGET_FRAMES),
            })
            all_groups.append(new_df)

    # Concatenate all markers and pitches
    return pl.concat(all_groups)


norm = normalize_frames_polars_interpolate(data)
norm.head()

shape: (5, 13)
┌────────┬───────────┬────────┬────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ userID ┆ sessionID ┆ height ┆ weight ┆ … ┆ y         ┆ z        ┆ markerID ┆ p_throws │
│ ---    ┆ ---       ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str       ┆ str    ┆ str    ┆   ┆ f64       ┆ f64      ┆ str      ┆ str      │
╞════════╪═══════════╪════════╪════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ 000830 ┆ 001615    ┆ 70     ┆ 193    ┆ … ┆ -0.195102 ┆ 1.510169 ┆ C7       ┆ R        │
│ 000830 ┆ 001615    ┆ 70     ┆ 193    ┆ … ┆ -0.196894 ┆ 1.510196 ┆ C7       ┆ R        │
│ 000830 ┆ 001615    ┆ 70     ┆ 193    ┆ … ┆ -0.198893 ┆ 1.510414 ┆ C7       ┆ R        │
│ 000830 ┆ 001615    ┆ 70     ┆ 193    ┆ … ┆ -0.200518 ┆ 1.511184 ┆ C7       ┆ R        │
│ 000830 ┆ 001615    ┆ 70     ┆ 193    ┆ … ┆ -0.2019   ┆ 1.512036 ┆ C7       ┆ R        │
└────────┴───────────┴────────┴────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [4]:
sample = norm.filter((pl.col('userID') == '000874') & (pl.col('sessionID') == '001562') & (pl.col('pitchNum') == '008'))
sample.head()

shape: (5, 13)
┌────────┬───────────┬────────┬────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ userID ┆ sessionID ┆ height ┆ weight ┆ … ┆ y        ┆ z        ┆ markerID ┆ p_throws │
│ ---    ┆ ---       ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str       ┆ str    ┆ str    ┆   ┆ f64      ┆ f64      ┆ str      ┆ str      │
╞════════╪═══════════╪════════╪════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081556 ┆ 1.548954 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081695 ┆ 1.548511 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081894 ┆ 1.547612 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.082146 ┆ 1.545997 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.082593 ┆ 1.543732 ┆ C7       ┆ R        │
└────────┴───────────┴────────┴────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [55]:
data.head()

shape: (5, 13)
┌────────┬───────────┬────────┬────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ userID ┆ sessionID ┆ height ┆ weight ┆ … ┆ y         ┆ z        ┆ markerID ┆ p_throws │
│ ---    ┆ ---       ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str       ┆ str    ┆ str    ┆   ┆ f64       ┆ f64      ┆ str      ┆ str      │
╞════════╪═══════════╪════════╪════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.068032 ┆ 1.581415 ┆ C7       ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.186507 ┆ 1.495219 ┆ CLAV     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ 0.22933   ┆ 0.071697 ┆ LANK     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.112121 ┆ 1.040045 ┆ LASI     ┆ R        │
│ 000002 ┆ 003034    ┆ 73     ┆ 207    ┆ … ┆ -0.085127 ┆ 1.731568 ┆ LBHD     ┆ R        │
└────────┴───────────┴────────┴────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [5]:
sample = sample.rename({'frame_norm': 'frame'})
sample.head()

shape: (5, 13)
┌────────┬───────────┬────────┬────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ userID ┆ sessionID ┆ height ┆ weight ┆ … ┆ y        ┆ z        ┆ markerID ┆ p_throws │
│ ---    ┆ ---       ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str       ┆ str    ┆ str    ┆   ┆ f64      ┆ f64      ┆ str      ┆ str      │
╞════════╪═══════════╪════════╪════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081556 ┆ 1.548954 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081695 ┆ 1.548511 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.081894 ┆ 1.547612 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.082146 ┆ 1.545997 ┆ C7       ┆ R        │
│ 000874 ┆ 001562    ┆ 73     ┆ 211    ┆ … ┆ 0.082593 ┆ 1.543732 ┆ C7       ┆ R        │
└────────┴───────────┴────────┴────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [13]:
# Making Polars DataFrame where each row is a pitch (i.e. x_marker_frame, y_marker_frame, z_marker_frame are columns made from x, y, z, frame, and markerID columns of df)

def create_pitch_df(df):
    # Create a Polars DataFrame where each row is a pitch
    pitch_df = df.pivot(
        index = ["userID", "sessionID", "pitchNum", "height", "weight", "pitchType", "pitchSpeed", "p_throws"],
        on = ['markerID', 'frame_norm'],
        values = ['x', 'y', 'z']
    )
    
    # Change from naming convention of x_{"C7",0} to x_C7_0 
    for col in pitch_df.columns:
        if col.startswith('x_') or col.startswith('y_') or col.startswith('z_'):
            new_col_name = col[0] + '_' + col.split('{')[1].split(',')[0].split('"')[1] + '_' + col.split('{')[1].split(',')[1][:-1]
            pitch_df = pitch_df.rename({col: new_col_name})

    return pitch_df

pitch_df = create_pitch_df(norm)
pitch_df.head()

shape: (5, 13_340)
┌────────┬───────────┬──────────┬────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ userID ┆ sessionID ┆ pitchNum ┆ height ┆ … ┆ z_T10_97 ┆ z_T10_98 ┆ z_T10_99 ┆ z_T10_100 │
│ ---    ┆ ---       ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str    ┆ str       ┆ str      ┆ str    ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64       │
╞════════╪═══════════╪══════════╪════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 000830 ┆ 001615    ┆ 006      ┆ 70     ┆ … ┆ 1.122508 ┆ 1.132782 ┆ 1.14151  ┆ 1.149718  │
│ 001644 ┆ 002926    ┆ 002      ┆ 67     ┆ … ┆ 0.934665 ┆ 0.940433 ┆ 0.944627 ┆ 0.949672  │
│ 000610 ┆ 001778    ┆ 002      ┆ 71     ┆ … ┆ 1.128943 ┆ 1.132536 ┆ 1.135254 ┆ 1.137682  │
│ 000359 ┆ 002734    ┆ 004      ┆ 72     ┆ … ┆ 0.975521 ┆ 0.983592 ┆ 0.993493 ┆ 1.005371  │
│ 001706 ┆ 003228    ┆ 006      ┆ 73     ┆ … ┆ 1.101008 ┆ 1.113996 ┆ 1.125626 ┆ 1.134344  │
└────────┴───────────┴──────────┴────────┴───┴──────────┴──────────┴──────────┴───────────┘